[DC-3035] TODO 리스트를 조회하는 기능 추가
jimin0127/kotlin-spring-todo pull request #1
Opened 2021-11-22 01:37 UTC by jimin0127

# tl;dr

DC-3035

TODO 리스트를 조회하는 기능을 추가합니다. 

# 주요 변경 사항
- 최근 등록일 순으로 TODO를 조회합니다. 
- h2 DB를 연결합니다. 
- Controller, Repository, Service를 추가합니다.

2021-11-23 02:36 UTC, veluxer62 requested changes

2021-11-23 02:36 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +}
요건 왜 필요한거에요?

2021-11-23 02:36 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    ): ResponseEntity<Any>{
P2: `ResponseEntity<Any>` 요런거 쓰면 혼나요 ^^

2021-11-23 02:36 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +            done: Boolean?,
P3: nullable은 되도록 지양해주세요.

2021-11-23 02:36 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +            return todoRepository.findAllByOrderByCreatedAtDesc(pageable)
P3: 요구사항은 `사용자는 완료된 TODO 리스트는 완료되지 않은 TODO 리스트와 나눠서 조회합니다.` 입니다. 즉 전체 조회는 없어요.

2021-11-23 02:36 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Todo.kt
> +class Todo(
P4: 테이블명은 Entity명을 기본값으로 따르기 때문에 동일하다면 굳이 적어주지 않아도 무방합니다.

2021-11-23 02:36 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Todo.kt
> +    var id: Long,
P3: ID는 생성자 매개변수가 아닌 자동 생성으로 바꿔주세요.

2021-11-23 02:36 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Todo.kt
> +    val todoContent: String = todoContent
Q: 다른 필드와 다르게 얘는 왜 불변 변수인가요?

2021-11-23 05:03 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Controller.kt
> +}
테스트용으로 작성했었습니다! 필요없으면 제거하겠습니다

2021-11-23 05:06 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Todo.kt
> +    val todoContent: String = todoContent
음 넵 불변 변수로 할지 가변 변수로 할지 고민하다가 이 필드만 불변으로 놔둔거 같네요... 
코틀린에서는 불변 변수랑 가변 변수 중 권장되는게 있나요?

2021-11-23 05:31 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Todo.kt
> +class Todo(
앗 그렇군요
https://github.com/jimin0127/kotlin-spring-todo/pull/1/commits/27d9d56667b144a7a051d77228293dccbb6f241f
반영했습니다

2021-11-23 05:33 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    ): ResponseEntity<Any>{
https://github.com/jimin0127/kotlin-spring-todo/pull/1/commits/abe0c440e1072d819d0f67bc4b61b4d986b08363
반영했는데 반환 타입이 이게 맞는지 모르겠어요 DTO로 변환해서 보내줘야하는건가용?

2021-11-23 05:34 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +            done: Boolean?,
https://github.com/jimin0127/kotlin-spring-todo/pull/1/commits/abe0c440e1072d819d0f67bc4b61b4d986b08363
반영했습니다!
이 커밋으로 아래도 함께 봐주시면 될것 같아요!

2021-11-23 06:04 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Todo.kt
> +    var id: Long,
https://github.com/jimin0127/kotlin-spring-todo/pull/2/files#:~:text=%40GeneratedValue(strategy%20%3D%20GenerationType.AUTO)
이걸 말씀하시는게 맞을까용..?

2021-11-23 06:07 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Controller.kt
> +}
18d9d3c95557e783d3b8a61000cf6bfbdff4e74c
제거했습니다

2021-11-23 06:24 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    ): ResponseEntity<Any>{
Spring에서는 ResponseEntity를 사용해도되고 그냥 Body 타입만 명시해도 알아서 ResponseEntity로 바꿔줍니다. 변경해주신대로 변경해도 됩니다. 다만 Entity를 그대로 내보내는건 좋아보이지 않네요.

2021-11-23 06:25 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Todo.kt
> +class Todo(
`@Table`도 안적어주셔도 되요

2021-11-23 06:26 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Todo.kt
> +    var id: Long,
네, 다른 PR에 있는거라 좀 어색하긴 하지만 반영된걸로 보겠습니다 :)

2021-11-23 06:28 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Todo.kt
> +    val todoContent: String = todoContent
불변이 권장되긴 합니다. 다만 Entity 객체는 Java Bean 정책을 따르므로 모두 가변인자로 선언되어야 합니다. 물론 kotlin에서 불변 변수로 선언해도 동작을 하긴 하는데, 여러 동작에 제약이 있어요. 그래서 저는 보통 캡슐화해서 외부에서 entity 속성을 변경하는 것을 방지합니다.

2021-11-23 06:29 UTC, veluxer62 reviewed
추가 코멘트 확인해주세요

2021-11-23 07:27 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Todo.kt
> +class Todo(
넵 rebase 로 반영했습니다!

2021-11-23 07:28 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    ): ResponseEntity<Any>{
https://github.com/jimin0127/kotlin-spring-todo/pull/1/commits/1b7d5e9ff2d8abe59326e3cf422dd53b45d06ab5
반영해봤습니다!

2021-11-23 07:34 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Todo.kt
> +    val todoContent: String = todoContent
https://github.com/jimin0127/kotlin-spring-todo/pull/1/commits/324af780d738b8f96c6b1b1485148749b5bb7fe5
가변 변수로 변경했습니다!

2021-11-24 04:21 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Todo.kt
> +    }
P2: 변환함수를 여기에 두면 도메인이 DTO를 의존하게 되는 구조로 됩니다.
아키텍쳐구성 시 `Presentation` -> `Application` -> `Domain` 방향으로 의존성을 가지는게 이상적입니다. 하지만 지금 구조는 `Domain` -> `Presentation`의 형태를 가지네요.
변환함수를 DTO로 옮기는건 어떠신가요?

2021-11-24 04:21 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +        return todo.map { it.toTodoDTO() }
P2: Service는 `Domain`레이어에 위치하게 됩니다. 그래서 위에서 설명드린바와 같이 `TodoDTO`를 의존하는 구조는 좋은 설계는 아닌것 같아요. Service는 Entity를 반환하도록 하는건 어떠세요?

2021-11-24 05:36 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +        return todo.map { it.toTodoDTO() }
https://github.com/jimin0127/kotlin-spring-todo/pull/1/commits/6bd1a88359c1850df9f534a861e0f1cc0c87999f
반영했습니다!

2021-11-24 05:37 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Todo.kt
> +    }
https://github.com/jimin0127/kotlin-spring-todo/pull/1/commits/2a23aea9c63cea525559c4ad785640502a0aded9
반영했는데 이게 맞을까요..??

2021-11-24 07:55 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Todo.kt
> +    }
네. DTO에 로직을 넣어주셔도 좋구요

2021-11-24 07:57 UTC, veluxer62 approved these changes

2021-11-25 16:45 UTC, merged