[DC-3027] TODO 리스트 추가 기능
jimin0127/kotlin-spring-todo pull request #2
Opened 2021-11-22 04:16 UTC by jimin0127

# tl;dr

DC-3035

TODO 리스트를 추가하는 기능을 추가합니다. 

# 주요 변경 사항
- TODO 내용을 받아서 TODO 리스트에 추가합니다.

2021-11-23 02:39 UTC, veluxer62 requested changes

2021-11-23 02:39 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    fun createTodo(@RequestBody todo: Todo): ResponseEntity<Any> {
P2: 외부에 노출되는 DTO를 Entity로 사용하는건 안좋은 패턴입니다. 동일하더라도 DTO로 변환하는게 좋아요

그리고 `ResponseEntity<Any>` 쓰시면 혼나요 ^^

2021-11-23 02:39 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +    }
P3: 코드 스타일 챙겨주세요. 그리고 `todo` 변수는 Inline 할 수 있겠네요.

2021-11-23 07:59 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    fun createTodo(@RequestBody todo: Todo): ResponseEntity<Any> {
5fc9631b719e128c97ac172bd9f5f782c88bf272
반영했습니다

2021-11-23 08:01 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +    }
넵! 요렇게 반영했습니다!

https://github.com/jimin0127/kotlin-spring-todo/pull/2/files#diff-5c95af22a165dc67cc793994fa8df97cf84af53fdcc5d3a66810152c81f62be8R27-R30

2021-11-24 04:25 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    }
Q: [CQS](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation)패턴을 보면 Command는 반환값을 가지지 않는게 이상적이라고 얘기합니다. 혹시 반환값이 필요한 이유가 있으신가요?

2021-11-24 04:25 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +        return todo.toTodoDTO()
P2: https://github.com/jimin0127/kotlin-spring-todo/pull/1#discussion_r755690560 여기서 드린 리뷰와 동일한데요 service는 domain 레이어에 위치하기 때문에 DTO에 의존하는것은 좋아보이지 않습니다.

2021-11-24 05:58 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    }
오 그렇군요.. 반환값이 필요한 이유는 없는 것 같습니다. 
예전부터 데이터를 삽입하고 나면 그 데이터를 반환해주고 확인하는 패턴으로 작업을 했어서 이번에도 그렇게 했었습니다.
반환값을 가지지 않는게 이상적이라면 그게 맞는 것 같습니다! 반영하겠습니다

2021-11-24 16:36 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    }
https://github.com/jimin0127/kotlin-spring-todo/pull/2/commits/c6103f9590058a1c9c25ea9e316d03fea3ac4314
반영했습니다

2021-11-24 16:38 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +        return todo.toTodoDTO()
https://github.com/jimin0127/kotlin-spring-todo/pull/2/commits/c6103f9590058a1c9c25ea9e316d03fea3ac4314
위 커밋과 동일한데요..! 반환값을 제거 했습니다

2021-11-25 02:01 UTC, veluxer62 requested changes

2021-11-25 02:01 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +        }
P2: 이 구문은 불필요해 보이네요. 이 코드는 예외가 발생하면 사용자든 개발자든 해당 오류를 인지하지 못하고 해당 요청은 끝나버립니다. 이렇게 하지 않는게 좋아요

2021-11-25 05:12 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +        }
7cf3ef5c1658b9d252363c50b9d50c88ce18f061
제거 했습니다..!

2021-11-25 14:02 UTC, veluxer62 approved these changes

2021-11-25 16:49 UTC, merged