[DC-3028] TODO 완료 처리 기능 추가
jimin0127/kotlin-spring-todo pull request #3
Opened 2021-11-22 04:50 UTC by jimin0127

# tl;dr

DC-3028

TODO 완료 처리하는 기능을 추가합니다

# 주요 변경 사항
- 완료처리하는 Service를 추가합니다. 
- 완료 처리를 하는 Controller를 추가합니다.

2021-11-23 02:49 UTC, veluxer62 requested changes

2021-11-23 02:49 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    fun toDone(@PathVariable id: Long): ResponseEntity<Any> {
P2: `ResponseEntity<Any>` 타입 바꿔주세요

2021-11-23 02:49 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +        var todo: Todo? = todoService.toDone(id)
P2: nullable한 값을 반환하는건 좋은 패턴이 아니에요. 왜냐하면 Client 코드가 반환값을 사용할때 매번 null 체크를 해야하기 때문이죠. 그래서 값이 만약 존재하지 않다면 throw를 던지는 패턴으로 가는게 좋습니다.

2021-11-23 02:49 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +        }
P2: Spring Data에 `findByIdOrNull`이라는 함수가 있어요. 다만 null을 반환하는건 앞의 리뷰에서 말씀 드린바와 같이 좋은 패턴이 아니기에 예외를 던지도록 하는게 좋아 보여요

```suggestion
        var todo: Todo? = todoRepository.findByIdOrNull(id)
```

2021-11-23 02:49 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +        todo.get().status = TodoStatus.DONE
P2: Entity의 상태를 직접 변경이 하지 않고 Entity의 행위로 정의해주세요

2021-11-23 09:36 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +        todo.get().status = TodoStatus.DONE
https://github.com/jimin0127/kotlin-spring-todo/pull/3/commits/141aef139cd546ccd37740050d49419251d841b6#diff-1172896697b9a4b22a78d53c76e3428a51bfcd62878d0671edc667e22b728850R31-R34
반영했습니다

2021-11-23 09:37 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +        }
https://github.com/jimin0127/kotlin-spring-todo/pull/3/files#diff-5c95af22a165dc67cc793994fa8df97cf84af53fdcc5d3a66810152c81f62be8R35-R38
반영했습니다

2021-11-23 09:38 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    fun toDone(@PathVariable id: Long): ResponseEntity<Any> {
https://github.com/jimin0127/kotlin-spring-todo/pull/3/files
반영했습니다! 아래도 같은 커밋으로 봐주시면 될 것 같아요

2021-11-24 04:35 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    fun toDone(@PathVariable id: Long): TodoDTO {
Q: 함수명의 의도를 잘 모르겠는데요, 혹시 어떤 의미로 `toDone`을 사용하신 걸까요?

2021-11-24 04:35 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +        val todo: Todo = todoRepository.findByIdOrNull(id) ?: throw IllegalArgumentException()
P3: optional 클래스에서는 `orElseThrow`를 제공해줍니다. 예외타입은 `NoSuchElementException`입니다.
```suggestion
        val todo: Todo = todoRepository.findById(id).orElseThrow()
```

2021-11-24 17:39 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +        val todo: Todo = todoRepository.findByIdOrNull(id) ?: throw IllegalArgumentException()
https://github.com/jimin0127/kotlin-spring-todo/pull/3/commits/caa0fa07ad85f58a3fef7585e8cfc2523f83b894
반영했습니다. 그런데 예외처리를 어떻게 해야할까요..? try-catch 문으로 처리하려고 했는데 그렇게 되면 try-catch문 바깥쪽에 어떤 값을 반환해야할지 모르겠어요...

2021-11-24 17:41 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    fun toDone(@PathVariable id: Long): TodoDTO {
완료처리를 한다는 의미로 그렇게 했었는데 명확하지 않은것 같네요!
https://github.com/jimin0127/kotlin-spring-todo/pull/3/commits/34789e26cd1fae49dbf77b465de7cc8c962fed5c
`updateToDone`으로 변경했습니다

2021-11-25 02:02 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    fun toDone(@PathVariable id: Long): TodoDTO {
네 함수명은 특별한 이유가 없다면 행위를 나타내는 동사로 표현되는게 좋다고 생각합니다. 그리고 되도록이면 문법을 잘지켜주는것도 가독성에 큰 영향을 미칩니다.

2021-11-25 02:04 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +        val todo: Todo = todoRepository.findByIdOrNull(id) ?: throw IllegalArgumentException()
Spring MVC에는`Exception Handler`가 있습니다. 예외가 발생하면 별도로 처리해 주어야 할 필요가 없다면 되도록 예외를 던져서 handler가 처리하도록 하는게 좋아요.

https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc

2021-11-25 02:08 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    fun updateToDone(@PathVariable id: Long): TodoDTO {
P3: 앞서 리뷰드린 [CQS](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation) 참고해주세요

2021-11-25 02:08 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +    override fun updateToDone(id: Long): Todo{
P3: 코드 스타일 챙겨주세요. 그리고 여기도 [CQS](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation)를 고민해주세요

2021-11-25 02:08 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Todo.kt
> +    fun setDone(): Unit {
P3: Unit은 꼭 필요하지 않으면 명시하지 않으셔도 됩니다.

2021-11-25 17:28 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Todo.kt
> +    fun setDone(): Unit {
https://github.com/jimin0127/kotlin-spring-todo/pull/3/commits/b09703fd0e4d33e18e607631b17d73af31f47056
반영했습니다

2021-11-25 17:29 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +    override fun updateToDone(id: Long): Todo{
https://github.com/jimin0127/kotlin-spring-todo/pull/3/commits/d676ee7294e5d9affc68c20e6f7c6563813de584
반환값이 필요없을 것 같아 제거했습니다!
아래도 같이 봐주세요

2021-11-26 10:16 UTC, veluxer62 approved these changes

2021-11-29 07:16 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +        val todo: Todo = todoRepository.findByIdOrNull(id) ?: throw IllegalArgumentException()
이 부분은 따로 반영해보고 따로 반영해보도록 하겠습니다! 일단 머지 할게여..!

2021-11-29 07:17 UTC, merged