[DC-3029] TODO 리스트 삭제 기능 추가
jimin0127/kotlin-spring-todo pull request #4
Opened 2021-11-22 05:28 UTC by jimin0127

# tl;dr

DC-3029

ID로 TODO 리스트를 삭제 하는 기능을 추가합니다. 

# 주요 변경 사항
- path의 id 값과 같은 TODO 리스트의 TODO를 삭제합니다.

2021-11-23 02:50 UTC, veluxer62 requested changes

2021-11-23 02:50 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    fun deleteTodo(@PathVariable id: Long): ResponseEntity<Any> {
P2: `ResponseEntity<Any>` 타입 바꿔주세요

2021-11-23 02:50 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +        return true
Q: 반환값이 boolean인 이유가 있나요?

2021-11-23 09:50 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    fun deleteTodo(@PathVariable id: Long): ResponseEntity<Any> {
https://github.com/jimin0127/kotlin-spring-todo/pull/4/commits/80e584dae4aaeabab08c36c616602d319445537e
반영했습니다!

2021-11-23 09:52 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +        return true
특별한 이유는 없습니다. 삭제 되었다는 의미와 삭제 되지 않았다는 의미로 boolean 값을 반환했습니다..
삭제된 Todo를 반환해주는게 더 좋을까요?

2021-11-24 04:37 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +        return true
[CQS](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation)를 보면 Command에는 반환값을 굳이 필요로 하지 않습니다. 특별한 이유가 없다면 반환타입은 없는게 좋아보여요

2021-11-24 04:37 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +        return deleted
P3: inline 처리할 수 있겠네요

2021-11-24 18:38 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +        return true
https://github.com/jimin0127/kotlin-spring-todo/pull/4/commits/1ef951ac367040f1077f7c8fcf5f7b6dd9754227
반환값이 없도록 반영했습니다!

2021-11-24 18:39 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Controller.kt
> +        return deleted
https://github.com/jimin0127/kotlin-spring-todo/pull/4/commits/1ef951ac367040f1077f7c8fcf5f7b6dd9754227
반환 값이 없도록 변경해서 한줄로 변경했습니다
위 커밋과 같습니다!

2021-11-25 02:10 UTC, veluxer62 requested changes

2021-11-25 02:10 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    fun deleteTodo(@PathVariable id: Long): Unit {
P3: 반환값이 없는 경우 Unit은 꼭 적지 않아도 됩니다.

2021-11-25 02:10 UTC, veluxer62 commented on src/main/kotlin/com/example/todo/Service.kt
> +        }
P2: https://github.com/jimin0127/kotlin-spring-todo/pull/2#discussion_r756521219 코멘트와 동일한 의견입니다.

2021-11-25 17:42 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Controller.kt
> +    fun deleteTodo(@PathVariable id: Long): Unit {
https://github.com/jimin0127/kotlin-spring-todo/pull/4/commits/66eaead182f6e8370105f6ba6a94a72ff25ca169
반영했습니다

2021-11-25 17:47 UTC, jimin0127 commented on src/main/kotlin/com/example/todo/Service.kt
> +        }
d323be48e0d9169669deec147d43e12da57ca23b
반영했습니당

2021-11-26 10:52 UTC, veluxer62 approved these changes

2021-11-29 07:22 UTC, merged